name: Lambda CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  BUCKET_NAME_DEV: ${{ secrets.bucket_dev }} # Name of the dev bucket. MUST BE ADDED AS A SECRET
  BUCKET_NAME_PROD: ${{ secrets.bucket_prod }} # Name of the prod bucket. MUST BE ADDED AS A SECRET
  S3_KEY_DEV: # Key of the zip package in dev bucket
  S3_KEY_PROD: # Key of the zip package in prod bucket
  LAMBDA_NAME_DEV: # Name of lambda function in dev environment
  LAMBDA_NAME_PROD: # Name of lambda function in prod environment
  PACKAGE_NAME_DEV: # Name of the zip file for dev
  PACKAGE_NAME_PROD: # Name of the zip file for prod
  AWS_REGION: # AWS Region (usually is just eu-west-1, which is Ireland)
  AWS_ACCOUNT_ID_DEV: ${{ secrets.account_dev }} # ID of the Dev account. MUST BE ADDED AS A SECRET
  AWS_ACCOUNT_ID_PROD: ${{ secrets.account_prod }} # ID of the Prod account. MUST BE ADDED AS A SECRET
  # LAMBDA_LAYER_NAME: # Name of the lambda layer. Uncomment if the lambda function has a layer attached
  # LAMBDA_LAYER_DESCRIPTION: # Description of the lambda layer. Uncomment if the lambda function has a layer attached

jobs:
  deploy:
    name: Upload to Amazon S3 and Update Lambda
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Folder # Creates the package for dev or prod based on the env variable
        run: |
          if [ "${{ github.event_name == 'push' }}" ]; then
            zip -r ${{ env.PACKAGE_NAME_DEV }} lambda_function.py
          else
            zip -r ${{ env.PACKAGE_NAME_PROD }} lambda_function.py
          fi

      - name: Configure AWS credentials # Generate credentials in STS to deploy lambdas
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ (github.event_name == 'push') && env.AWS_ACCOUNT_ID_DEV || env.AWS_ACCOUNT_ID_PROD }}:role/github-identity-provider-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy files to the S3 bucket #Deploys the new code to S3
        run: |
          aws s3 cp ${{ (github.event_name == 'push') && env.PACKAGE_NAME_DEV || env.PACKAGE_NAME_PROD }} s3://${{ (github.event_name == 'push') && env.BUCKET_NAME_DEV || env.BUCKET_NAME_PROD }}/${{ (github.event_name == 'push') && env.S3_KEY_DEV || env.S3_KEY_PROD }}

      - name: Update the code in lambda
        run: |
          aws lambda update-function-code --function-name ${{ (github.event_name == 'push') && env.LAMBDA_NAME_DEV || env.LAMBDA_NAME_PROD }} --s3-bucket ${{ (github.event_name == 'push') && env.BUCKET_NAME_DEV || env.BUCKET_NAME_PROD }} --s3-key ${{ (github.event_name == 'push') && env.S3_KEY_DEV || env.S3_KEY_PROD }} #Deploys the new version of the lambda code
       #  aws lambda publish-layer-version --layer-name ${{ env.LAMBDA_LAYER_NAME }} --description ${{ env.LAMBDA_LAYER_DESCRIPTION }} --content S3Bucket=${{ env.BUCKET_NAME }},S3Key=${{ env.LAMBDA_LAYER_S3_KEY }} --compatible-runtimes python3.11
       #  LATEST_LAYER_ARN=$(aws lambda list-layer-versions --layer-name ${{ env.LAMBDA_LAYER_NAME }} --query 'LayerVersions[0].LayerVersionArn' --region ${{ env.AWS_REGION }} --output text)
